#Borrowed from https://github.com/pele-python/mcpele

language: python
python:
    - 2.7

env:
  - MPI=openmpi

virtualenv:
  system_site_packages: true

branches:
  only:
    - master

before_install:
  # Use miniconda and conda packages to speed up dependency setup (principally 
  # borrowed from https://gist.github.com/dan-blanchard/7045057
  # and https://github.com/Jorge-C/ordination/blob/master/.travis.yml
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran lcov
  - gem install coveralls-lcov
  - test $MPI == openmpi && MPIPACKAGES='openmpi-bin openmpi-dev'          || true
  - sudo apt-get install -qq $MPIPACKAGES
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # Update conda itself
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  # Useful for debugging any issues with conda
  - conda info -a
  # matplotlib needs a DISPLAY
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"


install:
# Build pele
  - conda create --yes -n pelenv python=$TRAVIS_PYTHON_VERSION nose pip cython numpy scipy matplotlib sqlalchemy networkx
  - source activate pelenv
  - pip install munkres hungarian pyro4 brewer2mpl coverage coveralls coveralls-merge mpi4py 
  # download and install pele
  - mkdir -p  $HOME/build/pele-python
  - cd $HOME/build/pele-python
  - git clone https://github.com/pele-python/pele.git
  - cd pele
  - python setup_with_cmake.py build_ext -i --fcompiler=gfortran
  - export PYTHONPATH="$PWD:$PYTHONPATH"
# build PyBCGA
  - cd $HOME/build/marktoakley
  - cd PyBCGA
  - python setup.py build
  - pwd

script:
  - nosetests -v --with-coverage bcga

after_success:
  - coveralls
