'''
Read structures from the database generated by the batch GA.
Run the run_batch.py script to generate a database.

@author: Mark Oakley
'''
import numpy as np
from pele.storage.database import Database
db = Database(db="mydatabase.sqlite")
minima=db.minima()
print(db.number_of_minima())
for i in minima:
    print(i.energy)
    print(np.reshape(i.coords,(-1,3)))
